# Generated by Django 4.2.7 on 2023-12-24 08:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('answer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_id', models.CharField(max_length=100)),
                ('answerer_id', models.CharField(max_length=100)),
                ('up', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='post-images')),
                ('answer_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_id', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='post-images')),
                ('like', models.IntegerField(default=0)),
                ('post_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('reply_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_id', models.CharField(max_length=50)),
                ('replier_id', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('reply_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
