# Generated by Django 4.2.7 on 2023-12-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_replies_answer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='answer_id',
            field=models.CharField(max_length=50),
        ),
    ]
