# Generated by Django 4.2.7 on 2023-12-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_replies_answer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='content',
            new_name='content_answer',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='content',
            new_name='content_post',
        ),
        migrations.RenameField(
            model_name='replies',
            old_name='content',
            new_name='content_replies',
        ),
    ]
