# Generated by Django 4.2.7 on 2023-12-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_content_answers_content_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replies',
            old_name='content_replies',
            new_name='content_reply',
        ),
    ]
