# Generated by Django 4.2.7 on 2023-12-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_content_replies_replies_content_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='replies',
            name='reply_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
