# Generated by Django 4.2.7 on 2023-11-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='hobi',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='jurusan',
            field=models.CharField(blank=True, choices=[('IPA', 'Ilmu Pengetahuan Alam'), ('IPS', 'Ilmu Pengetahuan Sosial')], max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='kelamin',
            field=models.CharField(blank=True, choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='kelas',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
