# Generated by Django 4.2.7 on 2023-11-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_person_first_name_remove_person_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nis',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='kelas',
            field=models.CharField(blank=True, choices=[('X', 'Sepuluh'), ('XI', 'Sebelas'), ('XII', 'Dua Belas')], max_length=50),
        ),
    ]
