# Generated by Django 4.2.7 on 2023-11-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_person_kelamin_person_jenis_kelamin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
    ]
