# Generated by Django 4.2.7 on 2023-12-22 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_person_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='hobi',
            new_name='bio',
        ),
    ]
